{{- if .Values.resources.mariadb.enabled -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-root-password
  namespace: "{{ .Release.Namespace }}"
spec:
  target:
    name: mariadb-root-password
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: mariadb-root-password-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mariadb-root-password-generator
spec:
  length: 32
  allowRepeat: false
  noUpper: false
{{- end }}
