{{- if .Values.resources.pihole.enabled -}}
{{- $pihole := .Values.resources.pihole -}}
{{- $global := .Values.global -}}
{{- $gwSvc := lookup "v1" "Service" "istio-ingress" "gateway" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: 'pihole-data'
spec:
  accessModes:
    - 'ReadWriteOnce'
  storageClassName: {{ $pihole.storage.storageClassName }}
  resources:
    requests:
      storage: {{ $pihole.storage.size | quote }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pihole"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "pihole"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "pihole"
  template:
    metadata:
      labels:
        app: "pihole"
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "53"
        proxy.istio.io/config: '{"proxyMetadata":{"ISTIO_META_DNS_CAPTURE":"false"}}'
    spec:
      containers:
        - name: "pihole"
          image: "{{ $pihole.image.repository }}:{{ $pihole.image.tag }}"
          imagePullPolicy: "{{ $pihole.image.pullPolicy }}"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          env:
            - name: TZ
              value: {{ $global.timezone | quote }}
            - name: FTLCONF_dns_listeningMode
              value: 'ALL'
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: pihole-password
                  key: password
          {{- with $pihole.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /etc/pihole
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "pihole-data"

---

apiVersion: v1
kind: Service
metadata:
  name: "pihole-http"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "pihole"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: "pihole"

---

apiVersion: v1
kind: Service
metadata:
  name: "pihole-dns"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "pihole"
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: "pihole"

---

apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: "pihole-private"
  namespace: "{{ .Release.Namespace }}"
spec:
  gateways:
    - "{{ .Release.Name }}/private"
    - mesh
  hosts:
    - "{{ $pihole.subdomain }}.{{ $global.domain }}"
  http:
    - route:
        - destination:
            host: "pihole-http"
            port:
              number: 80
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: "pihole-mesh"
  namespace: "{{ .Release.Namespace }}"
spec:
  hosts:
    - "{{ $pihole.subdomain }}.{{ $global.domain }}"
  ports:
    - number: 80
      name: http
      protocol: HTTP
    - number: 443
      name: https
      protocol: HTTPS
  {{- if $gwSvc }}
  resolution: STATIC
  {{- else }}
  resolution: DNS
  {{- end }}
  location: MESH_INTERNAL
  endpoints:
    {{- if $gwSvc }}
    - address: {{ $gwSvc.spec.clusterIP }}
      ports:
        https: 443
    {{- else }}
    - address: gateway.istio-ingress.svc.cluster.local
      ports:
        https: 443
    {{- end }}
{{- end }}
