{{- if .Values.resources.postgresCluster.enabled -}}
{{- $pg := .Values.resources.postgresCluster -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-options: Delete=false

spec:
  instances: {{ $pg.instances }}
  imageName: {{ $pg.image }}
  storage:
    size: {{ $pg.storage.size }}
    storageClass: {{ $pg.storage.storageClassName }}
  managed:
    roles:
      - name: controller
        ensure: present
        comment: Control databases
        connectionLimit: -1
        inherit: true
        login: true
        superuser: true
        inRoles:
        - pg_monitor
        - pg_signal_backend
        passwordSecret:
          name: postgres-cluster-controller
{{- end }}
