{{- if .Values.resources.postgresCluster.enabled -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-cluster-controller
  namespace: "{{ .Release.Namespace }}"
spec:
  refreshInterval: "0"
  target:
    name: postgres-cluster-controller
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ "{{" }} `controller` {{ "}}" }}"
        password: "{{ "{{" }} .password {{ "}}" }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: postgres-controller-password-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-controller-password-generator
spec:
  length: 32
  encoding: hex
  allowRepeat: false
  noUpper: false
  secretKeys:
    - password
{{- end }}
