---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  description: "Project for homelab apps"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core
  source:
    repoURL: {{ .Values.source.repoUrl | quote }}
    targetRevision: {{ .Values.source.targetRevision | quote }}
    path: charts/core
    helm:
      values: |
        {{- $base := include "homelab.operatorValues" . -}}
        {{- include "homelab.mergeOverrides" (dict "base" $base "overrides" .Values.overrides.operators) | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    {{- include "homelab.syncPolicy" . | nindent 4 }}
