{{- if .Values.features.demo }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: {{ .Values.source.repoUrl | quote }}
    targetRevision: {{ .Values.source.targetRevision | quote }}
    path: charts/demo
    helm:
      values: |
        gatewayAddress: {{ .Values.platform.gatewayAddress }}
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    {{- include "homelab.syncPolicy" . | nindent 4 }}
    managedNamespaceMetadata:
      labels:
        istio.io/rev: default
        istio-injection: enabled
        homelab.mortenolsen.pro/mesh-isolation: skip
{{- end }}
