---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ .Values.monitor.project }}"
  namespace: argocd
spec:
  description: "Project for monitoring stack"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: "{{ .Values.monitor.project }}"
  source:
    repoURL: "{{ .Values.repoUrl }}"
    targetRevision: "{{ .Values.revision }}"
    path: charts/monitor
    helm:
      values: |
        project: "{{ .Values.monitor.project }}"
        {{- if .Values.monitor.values }}
        {{- toYaml .Values.monitor.values | nindent 8 }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio.io/rev: default
        istio-injection: enabled
