---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shared
  namespace: argocd
spec:
  description: "Project for homelab apps"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: shared
  source:
    repoURL: {{ .Values.source.repoUrl | quote }}
    targetRevision: {{ .Values.source.targetRevision | quote }}
    path: charts/shared
    helm:
      values: |
        {{- $base := include "homelab.platformValues" . -}}
        {{- include "homelab.mergeOverrides" (dict "base" $base "overrides" .Values.overrides.platform) | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: shared
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.emitWarning
        - .spec.rules[]?.skipBackgroundRequests
        - .spec.validationFailureAction
        - .status
  syncPolicy:
    {{- include "homelab.syncPolicy" . | nindent 4 }}
    managedNamespaceMetadata:
      labels:
        istio.io/rev: default
        istio-injection: enabled
        homelab.mortenolsen.pro/mesh-isolation: skip
      annotations:
        volsync.backube/privileged-movers: "true"
