---
# Platform services — infrastructure and access
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: platform-services
  namespace: "{{ .Release.Namespace }}"
  labels:
    release: prometheus-operator
spec:
  interval: 60s
  scrapeTimeout: 10s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      static:
        - http://argocd-server.argocd.svc.cluster.local
        - http://prometheus-operator-grafana.monitoring.svc.cluster.local
        - http://prometheus-operator-kube-p-alertmanager.monitoring.svc.cluster.local:9093
      labels:
        probe_group: platform
