{{- if .Values.resources.grafanaAdminSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: "{{ .Release.Namespace }}"
spec:
  refreshInterval: "0"
  target:
    name: grafana-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      data:
        admin-user: "{{ "{{" }} `admin` {{ "}}" }}"
        admin-password: "{{ "{{" }} .password {{ "}}" }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grafana-admin-password-generator
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-admin-password-generator
spec:
  length: 32
  encoding: base64
  allowRepeat: false
  noUpper: false
  secretKeys:
    - password
{{- end }}
