apiVersion: v2
name: homelab-common
description: Shared Helm library chart for deploying applications on the homelab platform
type: library
version: 0.1.8
keywords:
  - homelab
  - kubernetes
  - library
  - common
home: https://github.com/morten-olsen/homelab-core
sources:
  - https://github.com/morten-olsen/homelab-core
maintainers:
  - name: Morten Olsen
